# This is a basic workflow to help you get started with Actions
name: update-herakles

# Controls when the workflow will run
on:
  push:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-herakles:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.HERAKLES_TOKEN }}
          repository: samizdapp/herakles
          event-type: push
          client-payload: '{"repository": "${{ github.repository }}"}'
